### ISSUE TITLE
error in ha 2022.8

### ISSUE THREAD

**Issue by matteos1** [moox-it/hass-moox-track#3]
Platform error device_tracker.moox_track - No module named 'pytraccar.api'

**Comment by moox-it** [comment]
Thank you so much for your feedback, we are going to investigate this issue and fix it as soon is possible.

**Comment by moox-it** [comment]
We are glad to inform that the issue has being fixed in the last release released today.
Please upgrade the component and reboot your HASS to solve it.
Regards
