### ISSUE TITLE
ImportError: cannot import name 'ApiClient' from 'pytraccar'

### ISSUE THREAD

**Issue by DavideSky** [moox-it/hass-moox-track#4]
Hi, I noticed that the moox integration is not working anymore. This is the error that it gives when it loads the configuration.yaml. I'm currently running Homeassistant 2022.8 in Python venv.

> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config.py", line 878, in async_process_component_config
>     platform = p_integration.get_platform(domain)
>   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 657, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 674, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/home/homeassistant/.homeassistant/custom_components/moox_track/device_tracker.py", line 9, in <module>
>     from pytraccar import (
> ImportError: cannot import name 'ApiClient' from 'pytraccar' (/srv/homeassistant/lib/python3.9/site-packages/pytraccar/__init__.py)

**Comment by moox-it** [comment]
Hi thank you, we released a version few weeks ago that fix this issue.
Could you please download the latest version and eventually reopen a ticket if the issue is still present?
