### ISSUE TITLE
ImportError: cannot import name 'ApiClient' from 'pytraccar'

### ISSUE THREAD

**Issue by DavideSky** [moox-it/hass-moox-track#5]
> Hi thank you, we released a version few weeks ago that fix this issue.
> Could you please download the latest version and eventually reopen a ticket if the issue is still present?
> 
> _Originally posted by @moox-it in https://github.com/moox-it/hass-moox-track/issues/4#issuecomment-1228036656_
> 

Hi, thank you for the reply, sadly the issue is still present even after I reinstalled the integration. I have version 1.3 which seems to be the latest one.

**Comment by moox-it** [comment]
We are so sorry to hear that,
we are going to deep investigate in this issue that you are having.
Unfortunately we are not able reproduce this error, so it can take some days to further investigate.
Just to be sure did you rebooted your HASS after installing the new version of our plugin?

**Comment by DavideSky** [comment]
Thank you for your help, I rebooted HASS and even the server that HASS is running on, but the error is still there. If you need any additional information about the error you can ask me and I will provide that to you.

**Comment by moox-it** [comment]
Thank you so much, 
we will try to reproduce the error in the following days and we will update this issue as soon as possible.
Thank you for your kind understanding.

**Comment by moox-it** [comment]
Dear @DavideSky , 
the latest version released today force the requirements used by the plugin itself so it should fix any issues with the API if you are using HASS >= 2022.8

Please consider to update to hass-moox-track V 1.3 or 1.4 **only if you are using HASS >= 2022.8** 
if you are **running a version of HASS prior to 2022.8** the correct plugin version to install is the older hass-moox-track V 1.2

Please let us know if this doesn't solve your issues.

**Comment by DavideSky** [comment]
@moox-it thank you so much for the excellent support, with the new 1.4 update the error is now gone and everything is working fine again. Once again, thank you for all the effort in solving the issue.

Have a nice day, ~Davide

**Comment by moox-it** [comment]
@DavideSky we are so glad that everything is now working fine, thank you so much for your kind words, any further assistance we are more than glad to help :)
Have a nice day and thank you for using our devices :)
